FROM node:20-alpine

WORKDIR /app

# Install dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm install

# Copy source code
COPY . .

# Expose React dev server port
EXPOSE 3000

CMD ["npm", "start"]